# Creating Data Frames using Dictionaries

### 1.Student DataFrame

In [19]:
import pandas as pd

student_data={
    "Name":["Sujin","Divo","Ani","Jerald","Rani"],
    "Maths":[96,97,98,99,100],
    "Science":[99,98,97,96,98]
            }
df = pd.DataFrame(student_data)

df

     Name  Maths  Science
0   Sujin     96       99
1    Divo     97       98
2     Ani     98       97
3  Jerald     99       96
4    Rani    100       98

## 2.Employee DataFrame

In [21]:
import pandas as pd

employee_data={
    "Name":["Sujin","Divo","Ani","Jerald","Rani"],
    "Department":["IT","HR","Finance","HR","IT"],
    "Salary":[10000,20000,30000,40000,45000]
}


df = pd.DataFrame(employee_data)
df

     Name Department  Salary
0   Sujin         IT   10000
1    Divo         HR   20000
2     Ani    Finance   30000
3  Jerald         HR   40000
4    Rani         IT   45000

### 3.Product Sales Data

In [26]:
product_sales_data = {
    "Product":["Laptop","TV","Mobile","Tablet"],
    "price":[70000,40000,20000,30000],
    "Quantity Sold":[10,8,25,16]
}

df = pd.DataFrame(product_sales_data)

df

  Product  price  Quantity Sold
0  Laptop  70000             10
1      TV  40000              8
2  Mobile  20000             25
3  Tablet  30000             16